<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Refresh</name>
   <tag></tag>
   <elementGuidId>d974b59f-d66b-4592-9554-0089bba64dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-captcha-refresh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p0']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dc4fd0d-93a9-42cc-87b0-039f9a7126a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-captcha-refresh</value>
      <webElementGuid>810a5e2f-16c8-4c6f-b7e6-355cbcff4d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchantpage/auth/login</value>
      <webElementGuid>60e98e40-d45b-4513-9e81-d12c09b67bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>241e0e2e-b6e1-45a6-8009-0cf335fe17b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p0&quot;)/div[@class=&quot;link-captcha-refresh&quot;]/a[@class=&quot;link-captcha-refresh&quot;]</value>
      <webElementGuid>aa56936a-6817-49a6-84b0-f4f80d837a44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p0']/div[2]/a</value>
      <webElementGuid>6b759f32-f2bc-4431-99ad-80f714f9589b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refresh')]</value>
      <webElementGuid>c89e08ce-4eb8-4c34-ab49-8548176b888d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASSWORD'])[1]/following::a[1]</value>
      <webElementGuid>e674daa9-b829-45dc-85a2-a06f018ba881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER NAME'])[1]/following::a[1]</value>
      <webElementGuid>4cc4eadc-86a9-448d-9b54-fb20103985d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>e6872ea2-09cf-4b38-bd8d-e174ae3900d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::a[1]</value>
      <webElementGuid>2a14df94-cf6a-4634-a4b3-12158d76fc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>da47dc6a-21d8-4a33-a61c-142228877a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchantpage/auth/login')]</value>
      <webElementGuid>0725fc8e-c35a-4f9f-b9e7-88c63027a5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a21ead4b-a2d3-4a15-8a25-e40bb5cbffde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchantpage/auth/login' and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>91dc61fe-3e99-455d-9039-b71e61032244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
