<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_Incorrect EmailUsername or password</name>
   <tag></tag>
   <elementGuidId>da51f8ba-f53b-4bd0-bc4c-60f30acae543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>center.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>daf02d0a-8ec1-4c1f-ad56-6c431f9427a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>948f6192-6797-4e14-ae34-b601b3627656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incorrect Email/Username or password</value>
      <webElementGuid>ec6abbf4-2b9f-405b-b8b2-16583e10ab9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/center[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>f31ff610-33ba-4e95-9231-ca33bbde84e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/center</value>
      <webElementGuid>5fa6ca13-79d9-401e-9b48-acd8aed3b4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASSWORD'])[1]/following::center[1]</value>
      <webElementGuid>82882eba-8a07-448b-ab2e-a5eea70f3a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USER NAME'])[1]/following::center[1]</value>
      <webElementGuid>fc496fab-619c-46d2-bfec-4aadaafd5ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::center[1]</value>
      <webElementGuid>1126bd74-000c-4af5-9a0e-47f2e5c775b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::center[1]</value>
      <webElementGuid>f2c6dcac-07ec-4a74-a2ea-2d2f69009c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incorrect Email/Username or password']/parent::*</value>
      <webElementGuid>ce715f95-2282-4a02-b687-e5b82ab2634d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center</value>
      <webElementGuid>65a18a1a-c200-4b25-9143-c071a1910874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'Incorrect Email/Username or password' or . = 'Incorrect Email/Username or password')]</value>
      <webElementGuid>ac4e3e99-f3aa-4066-81ba-46a46b4142a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
